"""a

Revision ID: 02669beb998e
Revises: 
Create Date: 2023-07-05 16:45:09.515210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02669beb998e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery',
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('receiver_name', sa.String(length=300), nullable=False),
    sa.Column('telephone_number', sa.String(length=35), nullable=False),
    sa.Column('street', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=35), nullable=False),
    sa.Column('is_deliveried', sa.Boolean(), nullable=False),
    sa.Column('dilivery_day', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('track_id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_city', sa.String(length=35), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=True),
    sa.Column('delivery_status_name', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_status_name'], ['status_name.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['delivery.track_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    op.drop_table('delivery')
    # ### end Alembic commands ###
