"""a

Revision ID: 0cbdee08d7f6
Revises: 96997d128b4b
Create Date: 2023-07-06 17:11:17.940916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cbdee08d7f6'
down_revision = '96997d128b4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
