"""a

Revision ID: 61c64158588f
Revises: 
Create Date: 2023-07-07 19:02:02.869648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61c64158588f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_status_name')
    op.drop_table('delivery_status_name_ref')
    op.drop_table('delivery_status')
    op.drop_table('delivery')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('delivery_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receiver_name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('telephone_number', sa.VARCHAR(length=35), autoincrement=False, nullable=False),
    sa.Column('street', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=35), autoincrement=False, nullable=False),
    sa.Column('is_deliveried', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('dilivery_day', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='delivery_pkey'),
    sa.UniqueConstraint('track_id', name='delivery_track_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('delivery_status',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('delivery_status_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('current_city', sa.VARCHAR(length=35), autoincrement=False, nullable=False),
    sa.Column('status_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delivery_status_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['delivery_status_id'], ['delivery_status_name.id'], name='delivery_status_delivery_status_id_fkey'),
    sa.ForeignKeyConstraint(['track_id'], ['delivery.track_id'], name='delivery_status_track_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='delivery_status_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('delivery_status_name_ref',
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status_name_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['delivery_status.id'], name='delivery_status_name_ref_status_id_fkey'),
    sa.ForeignKeyConstraint(['status_name_id'], ['delivery_status_name.id'], name='delivery_status_name_ref_status_name_id_fkey'),
    sa.PrimaryKeyConstraint('status_id', 'status_name_id', name='delivery_status_name_ref_pkey')
    )
    op.create_table('delivery_status_name',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='delivery_status_name_pkey')
    )
    # ### end Alembic commands ###
