"""a

Revision ID: 62e50edcd941
Revises: 0cbdee08d7f6
Create Date: 2023-07-06 17:15:55.997524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e50edcd941'
down_revision = '0cbdee08d7f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
