"""a

Revision ID: 96997d128b4b
Revises: 02669beb998e
Create Date: 2023-07-05 16:45:59.428977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96997d128b4b'
down_revision = '02669beb998e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery', 'is_deliveried')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('is_deliveried', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
